# Generated by Django 4.1.4 on 2023-01-09 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter phone in format +380XXXXXXXXX', regex='^\\+?3?8?[- 0]?[- (]?[- 0(]?[0-9]{2}\\)?([ -]?[0-9]){7}')]),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
