# Generated by Django 4.1.4 on 2022-12-17 15:53

from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('video', models.FileField(upload_to=main_page.models.About.get_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=main_page.models.Chefs.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('link_twitter', models.URLField(blank=True)),
                ('link_facebook', models.URLField(blank=True)),
                ('link_instagram', models.URLField(blank=True)),
                ('link_linkedin', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(upload_to=main_page.models.Events.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('date_stop_event', models.DateTimeField()),
            ],
            options={
                'ordering': ('date_stop_event',),
            },
        ),
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('photo', models.ImageField(upload_to=main_page.models.RestaurantPhoto.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('profession', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to=main_page.models.Review.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('date_review', models.DateTimeField()),
            ],
            options={
                'ordering': ('date_review',),
            },
        ),
        migrations.CreateModel(
            name='StartPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('photo', models.FileField(upload_to=main_page.models.StartPage.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='WhyUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ingredients', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=main_page.models.Dish.get_file_name)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.dishcategory')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
