# Generated by Django 4.1.4 on 2022-12-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
