# Generated by Django 4.1.4 on 2022-12-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[('1', 1), ('22', 2), ('333', 3), ('4444', 4), ('55555', 5)]),
        ),
    ]
