# Generated by Django 4.1.4 on 2022-12-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[('1', 1), ('11', 2), ('111', 3), ('1111', 4), ('11111', 5)]),
        ),
    ]
