# Generated by Django 4.1.4 on 2022-12-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_userreservation_about_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
