# Generated by Django 4.1.4 on 2022-12-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_userreservation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservation',
            name='future_date_reserve',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreservation',
            name='future_time_reserve',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
