# Generated by Django 4.1.4 on 2022-12-21 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_userreservation_future_date_reserve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70, validators=[django.core.validators.RegexValidator(message='Enter a valid email address', regex='[\\da-zA-Z](-?[_\\da-zA-Z])*-?@([\\da-zA-Z]+\\.)*[a-z]{2,6}')])),
                ('subject_message', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('manager_date_processed', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='email',
            field=models.CharField(blank=True, max_length=70, validators=[django.core.validators.RegexValidator(message='Enter a valid email address', regex='[\\da-zA-Z](-?[_\\da-zA-Z])*-?@([\\da-zA-Z]+\\.)*[a-z]{2,6}')]),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='future_date_reserve',
            field=models.DateField(validators=[django.core.validators.RegexValidator(message='Enter date in format "0000-00-00"', regex='\\d{2,4}\\d([ -,.]{1,2}){2}')]),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter phone in format +380XXXXXXXXX', regex='^\\+?3?8?[ -(]?0 ?\\(?\\d{2}\\)?([ -]?\\d{7})')]),
        ),
    ]
