# Generated by Django 4.1.4 on 2022-12-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_alter_dish_description_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
