# Generated by Django 4.1.4 on 2022-12-27 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_alter_userreservation_future_date_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 16, 5, 25, 607864)),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 16, 5, 25, 606866)),
        ),
    ]
