# Generated by Django 4.1.4 on 2022-12-27 14:28

import datetime
from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_alter_usermessage_date_alter_userreservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startpage',
            name='photo',
            field=models.FileField(upload_to=main_page.models.NewFileName.get_file_name),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 16, 28, 9, 30749)),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 16, 28, 9, 30749)),
        ),
    ]
