# Generated by Django 4.1.4 on 2023-01-09 21:48

from django.db import migrations, models
import django_google_maps.fields
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0050_alter_about_photo_alter_about_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.NewFileName.get_file_name),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(upload_to=main_page.models.NewFileName.get_file_name),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.NewFileName.get_file_name),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.NewFileName.get_file_name),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.NewFileName.get_file_name),
        ),
        migrations.AlterField(
            model_name='restaurantphoto',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.NewFileName.get_file_name),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.NewFileName.get_file_name),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='photo',
            field=models.FileField(upload_to=main_page.models.NewFileName.get_file_name),
        ),
    ]
